[package]
name = "combine-slow-compile"
version = "0.1.0"
authors = ["Markus Westerlind <markus.westerlind@distilnetworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
combine = "3"
either = "1"
